# Generated by Django 5.2.6 on 2025-09-06 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quote',
            name='unique_source_text',
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('text',), name='unique_text', violation_error_message='Цитата уже существует для этого источника'),
        ),
    ]
